### PR TITLE
Add an option of timeout duration for executing command

### PR DESCRIPTION
**Pull request by taku-k**
## What
This pull-request introduces the option for specifying a duration after which a command execution will be timeout.

## Why
Running a slightly heavy check command will be easily timeout, so users should be able to adjust the timeout duration.

### CODE REVIEW

**Comment by Songmu** [comment]
That's a good pull request! We wanted to implement it for a long time.

I point out two points.

## Option name

I think `timeout_seconds` would be better.

## naming `context` is confusing

I think it is better not to use context in naming except for the standard context package
in Go world.

How about naming it as `CommandOption` and adding it to the end of the argument?

(In the first place, the package name util is not good itself. There is room for
improvement there.)

**Comment by taku-k** [comment]
Thank you for the review.
I followed your advice.

**Comment by Songmu** [comment]
Thanks for quick fixing.

One more. You should set `timeoutDururation` for action in `buildCheckPlugin`.

**Comment by taku-k** [comment]
I miss it. Thank you.

**Comment by Songmu** [comment]
Thanks! I

**Pull request merged**
