### PR TITLE
Migrate to mackerelio/golib/logging

### PR DESCRIPTION
**Pull request by astj**
ref: https://github.com/mackerelio/golib/blob/master/logging/logger.go

I'd like to remove mackerel-agent/logging in near future, but we cannot do it now because plugins are still using it.

### CODE REVIEW

**Comment by Songmu** [comment]
Please replace the plugin side first. The situation where logger and logging coexist is likely to cause confusion.

**Comment by Songmu** [comment]
Merge it after removing mackerel-agent/logging

**Comment by Songmu** [comment]
LGTM

**Comment by astj** [comment]
Thanks!

**Pull request merged**
