### PR TITLE
update for windows

### PR DESCRIPTION
**Pull request by daiksy**
- rename few metric keys 
- change source few metrics

### CODE REVIEW

**Comment by mechairoi** [comment]
LGTM! :full_moon:

**Comment by mattn** [comment]
don't you fix https://github.com/mackerelio/mackerel-agent/commit/6aa01da10fb372b6d08849e9923d6fd9e0974a19#commitcomment-10816383 ?

**Comment by daiksy** [comment]
https://github.com/mackerelio/mackerel-agent/pull/81/files#diff-30f3b6a98d65c07c03e6c7eb3874e81bR64

thanks for your checked!
I think modified it on this commit.

**Comment by mattn** [comment]
Ah, i missed it.

**Pull request merged**
