### PR TITLE
introduce Songmu/timeout for interrupting long time plugin execution

### PR DESCRIPTION
**Pull request by Songmu**

### CODE REVIEW

**Comment by daiksy** [comment]
LGTM!!!

**Comment by mattn** [comment]
On windows, cwd is not set https://github.com/mackerelio/mackerel-agent/blob/c6ffde9548957c3d339498f07127f466ae6a879d/util/util_windows.go

Right?

**Comment by mattn** [comment]
Ooops, sorry. `"pushd "+wd` is done.

**Comment by mattn** [comment]
BTW, why don't you use `command.Dir`? Considering UNC PATHs?

**Comment by mechairoi** [comment]
> BTW, why don't you use command.Dir? Considering UNC PATHs?

Default `command.Dir` means cwd <http://golang.org/pkg/os/exec/#Cmd>
, but <https://github.com/mackerelio/mackerel-agent/blob/c6ffde9548957c3d339498f07127f466ae6a879d/metrics/windows/plugin_test.go#L22> is failed without `pushd`. Probably `cmd /c` don't `dir` to cwd on running. However I didn't considering UNC PATHs.

**Comment by Songmu** [comment]
@mattn Thank you for the comment. We expect to enhance windows support.

This p-r is not for windows, so merge and close it.

**Comment by mattn** [comment]
:ok_woman:

**Pull request merged**
